### ISSUE TITLE
Adding packages for mysql and pgsql

### ISSUE THREAD

**Issue by muellerlukas** [tingvarsson/docker.mumble#1]
Hi,

I just found this docker-image. Works great, but on default there is no support for Mysql or PGSQL.

So I suggest adding the alpine packages "qt5-qtbase-mysql" and "qt5-qtbase-postgresql" to the dockerfile/image.

**Comment by tingvarsson** [comment]
Hi,

Not sure if I want to do that.

I have had an ambition to keep the images minimal and close to upstream, as well as primarily satisfy only my own needs.
However, the more concerning aspect would be that mumble themselves don't really recommend anything besides SQLite.

From their wiki:
> The default is QSQLITE, which is the SQLite database driver. Murmur does it's best to speak sensible, standards-compliant SQL - so you may have luck with any of the other database drivers supported by QSql - but note that SQLite is the most tested configuration followed very distantly behind by MySQL.

Are there any cool use cases with other backends?

And I hope you are aware you can always expand the image with your own customization if you like.

**Comment by muellerlukas** [comment]
Hi,
thanks for your patience.

I currently use the mysql-option because I sync my phpbb-permissions with the Mumble-Server. That is impossible with sqlite cause only one proccess can open the database.

Yeah, I know I can expand the image. That's what I currently do. I thought it would be a nice addition to your image.

**Comment by tingvarsson** [comment]
Reconsidered and did the proposed change. Since its only official packages I don't see much harm, or need to make sure it works other than it would with upstream.

Please give feedback if it is good enough for your needs.

**Comment by muellerlukas** [comment]
Works like a charm with mysql. Thanks. :)

**Comment by tingvarsson** [comment]
No problemo. Thanks for the suggestion after all.
